'use client';

import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Period = 'DAILY' | 'WEEKLY' | 'MONTHLY';
type MF = { id:number; name:string; code:string; category:string; nav:number|null; navDate:string|null; daily:number; weekly:number; monthly:number; rsi:number; belowHigh:number; opportunity:number; discount:number; total:number };
type Market = { symbol:string; ticker:string; name:string; category:string; group:string; current:number|null; date:string|null; daily:number; weekly:number; monthly:number; threeMonth:number; sixMonth:number; drawdown:number; high52:number; low52:number; rsi:number; trend:number; valueScore:number; momentumScore:number; setup:number; state:string; points:{date:string;close:number}[]; error:string|null };

const pct=(n:number)=>`${n>=0?'+':''}${n.toFixed(2)}%`;
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const scoreColor=(n:number)=>n>=70?'#16a34a':n>=55?'#d97706':'#dc2626';
const periodLabel=(p:Period)=>p==='DAILY'?'1D':p==='WEEKLY'?'1W':'1M';
function Score({v}:{v:number}){return <span className="score" style={{color:scoreColor(v),background:`${scoreColor(v)}12`}}>{v.toFixed(0)}</span>}
function Change({v}:{v:number}){return <span className={v>=0?'up':'down'}>{pct(v)}</span>}
function Skeleton({className=''}){return <div className={`skeleton ${className}`}/>}

export default function Home(){
 const [period,setPeriod]=useState<Period>('WEEKLY');
 const [mfs,setMfs]=useState<MF[]>([]); const [market,setMarket]=useState<Market[]>([]);
 const [loading,setLoading]=useState(true); const [marketLoading,setMarketLoading]=useState(true); const [error,setError]=useState(''); const [marketError,setMarketError]=useState('');
 const [tab,setTab]=useState<'OVERVIEW'|'MF'|'ETF'|'SECTOR'>('OVERVIEW'); const [selectedMF,setSelectedMF]=useState<MF|null>(null); const [selectedETF,setSelectedETF]=useState<Market|null>(null);
 const [history,setHistory]=useState<{date:string;nav:number}[]>([]); const [historyLoading,setHistoryLoading]=useState(false); const [amount,setAmount]=useState(10000); const [weight,setWeight]=useState(60);
 const load=async(refresh=false)=>{setLoading(true);setMarketLoading(true);setError('');setMarketError('');const q=refresh?'?refresh=1':'';
  try{const r=await fetch(`/api/dashboard${q}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'MF NAV unavailable');setMfs(j.rows||[]);if(j.errors?.length)setError(`${j.errors.length} mutual funds could not be loaded from MFAPI.`)}catch(e){setError(e instanceof Error?e.message:'Unable to load mutual fund NAV data.')}finally{setLoading(false)}
  try{const r=await fetch(`/api/market${q}`,{cache:'no-store'});const j=await r.json();setMarket([...(j.etfs||[]),...(j.sectors||[])]);if(j.status==='ERROR')setMarketError('Market/ETF feed is unavailable right now.')}catch(e){setMarketError(e instanceof Error?e.message:'Unable to load ETF and sector data.')}finally{setMarketLoading(false)}};
 const loadHistory=async(code:string)=>{setHistoryLoading(true);try{const r=await fetch(`/api/nav?code=${code}`,{cache:'no-store'});const j=await r.json();setHistory(j.data||[])}catch{setHistory([])}finally{setHistoryLoading(false)}};
 useEffect(()=>{load()},[]); useEffect(()=>{if(selectedMF)loadHistory(selectedMF.code)},[selectedMF]);
 const mfScore=(r:MF)=>{const ret=period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly;return Math.max(0,Math.min(100,r.opportunity*.62+r.discount*.18+(50+ret*(period==='DAILY'?8:period==='WEEKLY'?3.8:1.8))*.20))};
 const marketScore=(r:Market)=>{const ret=period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly;return Math.max(0,Math.min(100,r.setup*.62+r.valueScore*.18+Math.max(0,Math.min(100,50+ret*(period==='DAILY'?8:period==='WEEKLY'?3.8:1.8)))*.20))};
 const rankedMF=useMemo(()=>[...mfs].sort((a,b)=>mfScore(b)-mfScore(a)),[mfs,period]); const etfs=useMemo(()=>market.filter(x=>x.category==='ETF'),[market]); const sectors=useMemo(()=>market.filter(x=>x.category==='SECTOR'),[market]);
 const rankedETF=useMemo(()=>[...etfs].sort((a,b)=>marketScore(b)-marketScore(a)),[etfs,period]); const rankedSector=useMemo(()=>[...sectors].sort((a,b)=>marketScore(b)-marketScore(a)),[sectors,period]);
 const allocation=useMemo(()=>{if(!mfs.length)return[];const raw=mfs.map(r=>Math.max(.001,r.opportunity*(weight/100)+r.discount*((100-weight)/100)));const sum=raw.reduce((a,b)=>a+b,0);return mfs.map((r,i)=>({...r,alloc:amount*raw[i]/sum})).sort((a,b)=>b.alloc-a.alloc)},[mfs,amount,weight]);
 const selectedSeries=history.slice(-365).map(x=>({...x,short:x.date.slice(5)}));
 return <main>
  <header className="pro-hero"><div className="hero-inner"><div className="topline"><div className="brand"><span className="brand-mark">S</span><div><div className="eyebrow">SMART SIP • MARKET INTELLIGENCE</div><h1>Smart SIP & Market Radar</h1><p>Mutual funds • ETFs • Gold & Silver • Sector rotation • rule-based signals</p></div></div><div className="hero-actions"><span className="secure-badge">● RULE-BASED</span><button className="refresh" onClick={()=>load(true)} disabled={loading||marketLoading}>↻ Refresh data</button></div></div><div className="hero-metrics"><span><b>19</b> Mutual Funds</span><span><b>16</b> ETFs</span><span><b>12</b> Sectors</span><span><b>3</b> horizons</span></div></div></header>
  <div className="page"><div className="notice"><b>Important:</b> Scores are historical, rule-based indicators. “Best”, “bullish” and “rally setup” labels describe the current data structure only; they are not predictions or guarantees of future returns. Mutual fund and ETF investments are subject to market risk.</div>
   <nav className="nav-tabs">{[['OVERVIEW','Command Center'],['MF','Mutual Funds'],['ETF','ETFs & Metals'],['SECTOR','Sector Radar']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{l}</button>)}<div className="period-tabs">{(['DAILY','WEEKLY','MONTHLY'] as Period[]).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div></nav>
   {(error||marketError)&&<div className="warning">⚠ {error||marketError}</div>}
   {tab==='OVERVIEW'&&<>
    <section className="hero-grid"><div className="panel spotlight"><div className="kicker">CURRENT WINDOW • {periodLabel(period)}</div><h2>Where is the strongest setup?</h2><p className="muted">Combined view of historical opportunity, recent weakness and trend structure.</p><div className="spot-grid"><div><small>MF #1</small>{rankedMF[0]?<><b>{rankedMF[0].name}</b><Change v={period==='DAILY'?rankedMF[0].daily:period==='WEEKLY'?rankedMF[0].weekly:rankedMF[0].monthly}/><Score v={mfScore(rankedMF[0])}/></>:<Skeleton className="small-sk"/>}</div><div><small>ETF #1</small>{rankedETF[0]?<><b>{rankedETF[0].symbol}</b><Change v={period==='DAILY'?rankedETF[0].daily:period==='WEEKLY'?rankedETF[0].weekly:rankedETF[0].monthly}/><Score v={marketScore(rankedETF[0])}/></>:<Skeleton className="small-sk"/>}</div><div><small>SECTOR #1</small>{rankedSector[0]?<><b>{rankedSector[0].name}</b><Change v={period==='DAILY'?rankedSector[0].daily:period==='WEEKLY'?rankedSector[0].weekly:rankedSector[0].monthly}/><Score v={marketScore(rankedSector[0])}/></>:<Skeleton className="small-sk"/>}</div></div></div>
     <div className="panel allocation-card"><div className="kicker">₹ SIP ENGINE</div><h2>Dynamic MF allocation</h2><div className="input-line"><label>Monthly SIP</label><input type="number" value={amount} min="1000" step="500" onChange={e=>setAmount(Math.max(1000,Number(e.target.value)||1000))}/></div><div className="slider-head"><span>Opportunity weight</span><b>{weight}%</b></div><input className="slider" type="range" min="0" max="100" value={weight} onChange={e=>setWeight(Number(e.target.value))}/><div className="alloc-list">{allocation.slice(0,5).map((r:any,i)=><div className="alloc-row" key={r.id}><span>{i+1}</span><b>{r.name}</b><strong>{money(r.alloc)}</strong></div>)}</div></div></section>
    <section className="section-head"><div><div className="kicker">QUICK RANKINGS</div><h2>Top opportunities — {periodLabel(period)}</h2><p>Historical setup ranking, not a buy signal.</p></div></section>
    <section className="three-grid"><RankPanel title="Mutual Funds" items={rankedMF.slice(0,5).map(r=>({name:r.name,ret:period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly,score:mfScore(r)}))} onClick={i=>{setTab('MF');setSelectedMF(rankedMF[i])}} loading={loading}/><RankPanel title="ETFs & Metals" items={rankedETF.slice(0,5).map(r=>({name:r.symbol,ret:period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly,score:marketScore(r)}))} onClick={i=>{setTab('ETF');setSelectedETF(rankedETF[i])}} loading={marketLoading}/><RankPanel title="Sector Leaders" items={rankedSector.slice(0,5).map(r=>({name:r.name,ret:period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly,score:marketScore(r)}))} onClick={()=>setTab('SECTOR')} loading={marketLoading}/></section>
    <section className="panel sector-panel"><div className="panel-head"><div><div className="kicker">ROTATION RADAR</div><h2>Sector strength / weakness map</h2><p>Green = stronger structure. Red = weaker structure. “Rally setup” is a rules-based recovery label, not a forecast.</p></div><span className="tag gold">12 sectors</span></div><div className="heatmap">{rankedSector.map(s=><SectorTile key={s.symbol} s={s} period={period}/>)}</div></section>
   </>}
   {tab==='MF'&&<MFView rows={rankedMF} period={period} loading={loading} onSelect={r=>setSelectedMF(r)} selected={selectedMF} history={selectedSeries} historyLoading={historyLoading}/>} 
   {tab==='ETF'&&<ETFView rows={rankedETF} period={period} loading={marketLoading} selected={selectedETF} onSelect={setSelectedETF}/>} 
   {tab==='SECTOR'&&<SectorView rows={rankedSector} period={period} loading={marketLoading}/>} 
   <footer className="footer"><span><b>Data:</b> MFAPI for mutual-fund NAV; Yahoo Finance market chart feed for ETFs/indices.</span><span><b>Method:</b> daily / weekly / monthly return + drawdown + RSI + trend structure.</span><span><b>Disclaimer:</b> Decision-support software, not investment advice.</span></footer>
  </div></main>
}

function RankPanel({title,items,onClick,loading}:{title:string;items:{name:string;ret:number;score:number}[];onClick:(i:number)=>void;loading:boolean}){return <div className="panel rank-panel"><div className="panel-head"><div><div className="kicker">RANKED</div><h2>{title}</h2></div><span className="tag">TOP 5</span></div>{loading?[1,2,3,4,5].map(i=><Skeleton key={i} className="rank-sk"/>):items.map((x,i)=><button className="rank-item" key={x.name} onClick={()=>onClick(i)}><span className="rank-index">0{i+1}</span><div><b>{x.name}</b><small><Change v={x.ret}/> {periodLabel('WEEKLY')} • setup</small></div><Score v={x.score}/></button>)}</div>}
function SectorTile({s,period}:{s:Market;period:Period}){const ret=period==='DAILY'?s.daily:period==='WEEKLY'?s.weekly:s.monthly;const tone=s.setup>=72?'strong':s.setup>=58?'positive':s.setup>=42?'watch':'weak';return <div className={`sector-tile ${tone}`}><div className="sector-top"><b>{s.name}</b><span>{pct(ret)}</span></div><div className="sector-bar"><i style={{width:`${s.setup}%`}}/></div><div className="sector-bottom"><span>Setup {s.setup.toFixed(0)}</span><span>{s.trend>=65?'BULLISH STRUCTURE':s.setup>=65?'RALLY SETUP':'WATCH'}</span></div></div>}
function MFView({rows,period,loading,onSelect,selected,history,historyLoading}:{rows:MF[];period:Period;loading:boolean;onSelect:(r:MF)=>void;selected:MF|null;history:{date:string;nav:number}[];historyLoading:boolean}){const ret=(r:MF)=>period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly;return <><section className="section-head"><div><div className="kicker">MUTUAL FUNDS</div><h2>19-fund opportunity board</h2><p>Daily, weekly and monthly views with transparent rule-based scoring.</p></div></section><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>#</th><th>Fund</th><th>NAV</th><th>{periodLabel(period)}</th><th>RSI</th><th>Below 52W High</th><th>Opportunity</th><th>Discount</th><th>Total</th></tr></thead><tbody>{loading?[1,2,3,4,5,6].map(i=><tr key={i}><td colSpan={9}><Skeleton className="row-sk"/></td></tr>):rows.map((r,i)=><tr className={selected?.id===r.id?'selected':''} key={r.id} onClick={()=>onSelect(r)}><td>{String(i+1).padStart(2,'0')}</td><td><b>{r.name}</b><small>{r.category} · {r.code}</small></td><td>{r.nav?`₹${r.nav.toFixed(2)}`:'—'}</td><td><Change v={ret(r)}/></td><td>{r.rsi.toFixed(0)}</td><td>{r.belowHigh.toFixed(1)}%</td><td><Score v={r.opportunity}/></td><td><Score v={r.discount}/></td><td><Score v={r.total}/></td></tr>)}</tbody></table></div></div>{selected&&<div className="panel"><div className="panel-head"><div><div className="kicker">SELECTED FUND</div><h2>{selected.name}</h2><p>Latest NAV {selected.nav?`₹${selected.nav.toFixed(2)}`:'—'} · {selected.navDate}</p></div><Score v={selected.total}/></div><div className="metric-cards"><Metric label="Daily" value={pct(selected.daily)}/><Metric label="Weekly" value={pct(selected.weekly)}/><Metric label="Monthly" value={pct(selected.monthly)}/><Metric label="RSI" value={selected.rsi.toFixed(0)}/></div><div className="detail-chart">{historyLoading?<Skeleton className="chart-sk"/>:history.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={history}><defs><linearGradient id="mfFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#c9a227" stopOpacity={.28}/><stop offset="1" stopColor="#c9a227" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf0f4" vertical={false}/><XAxis dataKey="date" tick={{fontSize:9}} minTickGap={35}/><YAxis tick={{fontSize:9}} domain={['auto','auto']}/><Tooltip/><Area type="monotone" dataKey="nav" stroke="#b38a16" fill="url(#mfFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="empty">NAV history unavailable</div>}</div></div>}</>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric-card"><small>{label}</small><b>{value}</b></div>}
function ETFView({rows,period,loading,selected,onSelect}:{rows:Market[];period:Period;loading:boolean;selected:Market|null;onSelect:(r:Market)=>void}){const ret=(r:Market)=>period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly;return <><section className="section-head"><div><div className="kicker">ETF RADAR</div><h2>Core ETFs + Gold & Silver + sector ETFs</h2><p>Daily / weekly / monthly relative setup using price weakness, trend and recovery structure.</p></div></section><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>#</th><th>ETF</th><th>Group</th><th>Price</th><th>{periodLabel(period)}</th><th>3M</th><th>Drawdown</th><th>RSI</th><th>Setup</th><th>View</th></tr></thead><tbody>{loading?[1,2,3,4,5,6].map(i=><tr key={i}><td colSpan={10}><Skeleton className="row-sk"/></td></tr>):rows.map((r,i)=><tr className={selected?.symbol===r.symbol?'selected':''} key={r.symbol} onClick={()=>onSelect(r)}><td>{String(i+1).padStart(2,'0')}</td><td><b>{r.symbol}</b><small>{r.name}</small></td><td><span className={r.group==='Gold & Silver'?'tag gold':'tag'}>{r.group}</span></td><td>{r.current?`₹${r.current.toFixed(2)}`:'—'}</td><td><Change v={ret(r)}/></td><td><Change v={r.threeMonth}/></td><td className={r.drawdown<-10?'down':'muted'}>{r.drawdown.toFixed(1)}%</td><td>{r.rsi.toFixed(0)}</td><td><Score v={r.setup}/></td><td><span className={`state ${r.state.toLowerCase()}`}>{r.state}</span></td></tr>)}</tbody></table></div></div>{selected&&<div className="panel"><div className="panel-head"><div><div className="kicker">ETF DETAIL</div><h2>{selected.name}</h2><p>{selected.symbol} · data date {selected.date||'—'}</p></div><div className="detail-score"><Score v={selected.setup}/><small>rule-based setup</small></div></div><div className="metric-cards"><Metric label="Daily" value={pct(selected.daily)}/><Metric label="Weekly" value={pct(selected.weekly)}/><Metric label="Monthly" value={pct(selected.monthly)}/><Metric label="6M" value={pct(selected.sixMonth)}/><Metric label="52W drawdown" value={pct(selected.drawdown)}/><Metric label="Trend" value={selected.trend.toFixed(0)}/></div></div>}</>}
function SectorView({rows,period,loading}:{rows:Market[];period:Period;loading:boolean}){const ret=(r:Market)=>period==='DAILY'?r.daily:period==='WEEKLY'?r.weekly:r.monthly;return <><section className="section-head"><div><div className="kicker">SECTOR ROTATION</div><h2>Which sectors are strong, weak or recovering?</h2><p>“Bullish structure” means price is above key moving-average structure. “Rally setup” is a historical recovery condition, not a forecast.</p></div></section><div className="panel"><div className="heatmap large">{loading?[1,2,3,4,5,6,7,8].map(i=><Skeleton key={i} className="tile-sk"/>):rows.map(s=><SectorTile key={s.symbol} s={s} period={period}/>)}</div></div><div className="three-grid sector-cards"><div className="panel"><div className="kicker">STRONGEST</div><h3>Top sectors</h3>{rows.slice(0,5).map(s=><div className="mini-line" key={s.symbol}><b>{s.name}</b><Change v={ret(s)}/><Score v={s.setup}/></div>)}</div><div className="panel"><div className="kicker">DEEPEST FALLS</div><h3>Most corrected</h3>{[...rows].sort((a,b)=>ret(a)-ret(b)).slice(0,5).map(s=><div className="mini-line" key={s.symbol}><b>{s.name}</b><Change v={ret(s)}/><span>{s.drawdown.toFixed(1)}% 52W</span></div>)}</div><div className="panel"><div className="kicker">RECOVERY WATCH</div><h3>Potential setups</h3>{rows.filter(s=>s.setup>=55).slice(0,5).map(s=><div className="mini-line" key={s.symbol}><b>{s.name}</b><span>{s.trend.toFixed(0)} trend</span><Score v={s.setup}/></div>)}</div></div></>}
