'use client';

import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Horizon='DAILY'|'WEEKLY'|'MONTHLY';
type MF={id:number;name:string;code:string;category:string;group:'EQUITY'|'GOLD'|'SILVER';nav:number|null;navDate:string|null;daily:number;weekly:number;monthly:number;ret3m:number;ret6m:number;ret1y:number;belowHigh:number;rsi:number;ma20:number;ma50:number;volatility:number;trend:number;drawdown:number;discount:number;opportunity:number;quality:number;momentum:number;risk:number;total:number;dataPoints:number};
type Market={symbol:string;ticker:string;name:string;category:'INDEX'|'SECTOR';current:number|null;date:string|null;weekly:number;monthly:number;quarter:number;drawdown:number;high52:number;low52:number;rsi:number;ma20:number;ma50:number;trend:number;setup:number;state:string;error:string|null};
const pct=(n:number)=>`${n>=0?'+':''}${n.toFixed(2)}%`;
const score=(n:number)=>Math.round(Math.max(0,Math.min(100,n)));
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const horizon=(p:Horizon)=>p==='DAILY'?'1D':p==='WEEKLY'?'1W':'1M';
const ret=(r:MF,p:Horizon)=>p==='DAILY'?r.daily:p==='WEEKLY'?r.weekly:r.monthly;
const marketRet=(r:Market,p:Horizon)=>p==='WEEKLY'?r.weekly:r.monthly;
const action=(r:MF)=>r.total>=72&&r.rsi<58?'ACCUMULATE':r.total>=65?'STRONG SETUP':r.total>=55?'WATCH':'REVIEW';
const actionClass=(a:string)=>a==='ACCUMULATE'||a==='STRONG SETUP'?'good':a==='WATCH'?'warn':'bad';
function Score({v}:{v:number}){const n=score(v);return <span className={`score ${n>=70?'score-good':n>=55?'score-warn':'score-bad'}`}>{n}</span>}
function Change({v}:{v:number}){return <span className={v>=0?'up':'down'}>{pct(v)}</span>}
function Skeleton({className=''}){return <div className={`skeleton ${className}`}/>}

export default function Home(){
 const [period,setPeriod]=useState<Horizon>('MONTHLY'); const [tab,setTab]=useState<'HOME'|'FUNDS'|'METALS'|'SECTORS'|'CAPS'>('HOME');
 const [mfs,setMfs]=useState<MF[]>([]); const [market,setMarket]=useState<Market[]>([]); const [loading,setLoading]=useState(true); const [marketLoading,setMarketLoading]=useState(true); const [error,setError]=useState(''); const [marketError,setMarketError]=useState('');
 const [selected,setSelected]=useState<MF|null>(null); const [history,setHistory]=useState<{date:string;nav:number}[]>([]); const [historyLoading,setHistoryLoading]=useState(false); const [sip,setSip]=useState(10000);
 const load=async(refresh=false)=>{setLoading(true);setMarketLoading(true);setError('');setMarketError('');const q=refresh?'?refresh=1':'';try{const r=await fetch(`/api/dashboard${q}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Mutual-fund data unavailable');setMfs(j.rows||[]);if(j.errors?.length)setError(`${j.errors.length} fund(s) could not be loaded. They are excluded from scoring.`)}catch(e){setError(e instanceof Error?e.message:'Mutual-fund data unavailable')}finally{setLoading(false)}try{const r=await fetch(`/api/market${q}`,{cache:'no-store'});const j=await r.json();setMarket(j.items||[]);if(j.status==='ERROR')setMarketError('Market-index/sector feed is unavailable. No score is assigned to unavailable data.')}catch(e){setMarketError(e instanceof Error?e.message:'Market data unavailable')}finally{setMarketLoading(false)}};
 const loadHistory=async(code:string)=>{setHistoryLoading(true);try{const r=await fetch(`/api/nav?code=${code}`,{cache:'no-store'});const j=await r.json();setHistory(j.data||[])}catch{setHistory([])}finally{setHistoryLoading(false)}};
 useEffect(()=>{load()},[]); useEffect(()=>{if(selected)loadHistory(selected.code)},[selected]);
 const equity=useMemo(()=>mfs.filter(x=>x.group==='EQUITY'),[mfs]); const gold=useMemo(()=>mfs.filter(x=>x.group==='GOLD'),[mfs]); const silver=useMemo(()=>mfs.filter(x=>x.group==='SILVER'),[mfs]);
 const rankedEquity=useMemo(()=>[...equity].sort((a,b)=>b.total-a.total),[equity]); const rankedGold=useMemo(()=>[...gold].sort((a,b)=>b.total-a.total),[gold]); const rankedSilver=useMemo(()=>[...silver].sort((a,b)=>b.total-a.total),[silver]);
 const weeklyLosers=useMemo(()=>equity.filter(x=>x.weekly<0).sort((a,b)=>a.weekly-b.weekly),[equity]); const monthlyLosers=useMemo(()=>equity.filter(x=>x.monthly<0).sort((a,b)=>a.monthly-b.monthly),[equity]);
 const goldWeeklyLosers=useMemo(()=>gold.filter(x=>x.weekly<0).sort((a,b)=>a.weekly-b.weekly),[gold]); const goldMonthlyLosers=useMemo(()=>gold.filter(x=>x.monthly<0).sort((a,b)=>a.monthly-b.monthly),[gold]); const silverWeeklyLosers=useMemo(()=>silver.filter(x=>x.weekly<0).sort((a,b)=>a.weekly-b.weekly),[silver]); const silverMonthlyLosers=useMemo(()=>silver.filter(x=>x.monthly<0).sort((a,b)=>a.monthly-b.monthly),[silver]);
 const indices=useMemo(()=>market.filter(x=>x.category==='INDEX'),[market]); const sectors=useMemo(()=>market.filter(x=>x.category==='SECTOR'),[market]); const weakestSector=useMemo(()=>[...sectors].sort((a,b)=>a.weekly-b.weekly)[0],[sectors]); const strongestSector=useMemo(()=>[...sectors].sort((a,b)=>b.setup-a.setup)[0],[sectors]);
 const allocation=useMemo(()=>{const top=rankedEquity.slice(0,5);if(!top.length)return[];const weights=top.map(x=>Math.max(1,x.total));const sum=weights.reduce((a,b)=>a+b,0);return top.map((x,i)=>({...x,allocation:sip*0.85*weights[i]/sum}));},[rankedEquity,sip]);
 const selectedSeries=history.slice(-365).map(x=>({...x,short:x.date.slice(5)}));
 return <main>
  <header className="pro-hero"><div className="hero-inner"><div className="topline"><div className="brand"><span className="brand-mark">S</span><div><div className="eyebrow">SMART SIP • LONG-TERM INVESTMENT INTELLIGENCE</div><h1>Mutual Fund Intelligence Dashboard</h1><p>Daily · Weekly · Monthly strength, weakness, quality, risk and accumulation signals</p></div></div><div className="hero-actions"><span className="secure-badge">● RULE-BASED • NO FORECASTS</span><button className="refresh" onClick={()=>load(true)} disabled={loading||marketLoading}>↻ Refresh data</button></div></div><div className="hero-metrics"><span><b>{mfs.length||23}</b> Mutual Funds</span><span><b>5</b> Market-Cap Indices</span><span><b>{sectors.length||11}</b> Sectors</span><span><b>3</b> Horizons</span></div></div></header>
  <div className="page"><div className="notice"><b>How to use:</b> All Score combines long-term quality, opportunity, discount, momentum and risk. A loser is only a recent decline; it is <b>not automatically a buy</b>. Accumulation labels are rule-based decision support, not investment advice or a promise of profit.</div>
   <nav className="nav-tabs">{[['HOME','Investment Radar'],['FUNDS','Mutual Funds'],['METALS','Gold & Silver MF'],['SECTORS','Sectors'],['CAPS','Market Caps']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{l}</button>)}<div className="period-tabs">{(['DAILY','WEEKLY','MONTHLY'] as Horizon[]).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div></nav>
   {(error||marketError)&&<div className="warning">⚠ {error||marketError}</div>}
   {tab==='HOME'&&<>
    <section className="hero-grid"><div className="panel spotlight"><div className="kicker">MARKET INTELLIGENCE • {horizon(period)}</div><h2>What is strongest, what has corrected?</h2><p className="muted">Use short-term weakness alongside long-term quality instead of chasing the biggest recent fall.</p><div className="spot-grid"><Spot label="#1 EQUITY" value={rankedEquity[0]?.name||'Loading…'} sub={rankedEquity[0]?`All Score ${score(rankedEquity[0].total)} · ${pct(ret(rankedEquity[0],period))}`:'—'}/><Spot label="WEEKLY WEAKEST SECTOR" value={weakestSector?.name||'Loading…'} sub={weakestSector?`${pct(weakestSector.weekly)} · RSI ${Math.round(weakestSector.rsi)}`:'—'}/><Spot label="STRONGEST SETUP" value={strongestSector?.name||'Loading…'} sub={strongestSector?`Setup ${score(strongestSector.setup)} · ${strongestSector.state}`:'—'}/></div></div><div className="panel allocation-card"><div className="kicker">LONG-TERM SIP ENGINE</div><h2>Illustrative allocation</h2><div className="input-line"><label>Monthly SIP</label><input type="number" value={sip} min="1000" step="500" onChange={e=>setSip(Math.max(1000,Number(e.target.value)||1000))}/></div><p className="microcopy">85% distributed across the top 5 equity scores; 15% reserved for diversification into Gold/Silver and market-cap opportunities.</p><div className="alloc-list">{allocation.map((r,i)=><div className="alloc-row" key={r.id}><span>{i+1}</span><b>{r.name}</b><strong>{money(r.allocation)}</strong></div>)}</div><div className="alloc-reserve"><span>Diversification reserve</span><b>{money(sip*.15)}</b></div></div></section>
    <section className="section-head"><div><div className="kicker">CORE EQUITY RADAR</div><h2>Top 5 Mutual Funds — All Score</h2><p>Highest-scoring equity funds for the selected evaluation horizon.</p></div><span className="tag gold">ALL SCORE</span></section><div className="five-grid">{loading?[1,2,3,4,5].map(i=><div className="panel" key={i}><Skeleton className="card-sk"/></div>):rankedEquity.slice(0,5).map((r,i)=><FundCard key={r.id} r={r} rank={i+1} period={period} onClick={()=>setSelected(r)}/>)}</div>
    <section className="two-grid"><LoserPanel title="Top Losers — Weekly" rows={weeklyLosers.slice(0,5)} period="WEEKLY" onSelect={setSelected}/><LoserPanel title="Top Losers — Monthly" rows={monthlyLosers.slice(0,5)} period="MONTHLY" onSelect={setSelected}/></section>
    <MarketCapSection indices={indices} loading={marketLoading} period={period}/><SectorSection sectors={sectors} loading={marketLoading} period={period}/><MetalsSection gold={rankedGold} silver={rankedSilver} goldW={goldWeeklyLosers} goldM={goldMonthlyLosers} silverW={silverWeeklyLosers} silverM={silverMonthlyLosers} onSelect={setSelected}/><LongTermSection/>
   </>}
   {tab==='FUNDS'&&<FundTable rows={rankedEquity} loading={loading} period={period} onSelect={setSelected}/>} {tab==='METALS'&&<MetalsSection gold={rankedGold} silver={rankedSilver} goldW={goldWeeklyLosers} goldM={goldMonthlyLosers} silverW={silverWeeklyLosers} silverM={silverMonthlyLosers} onSelect={setSelected}/>} {tab==='SECTORS'&&<SectorSection sectors={sectors} loading={marketLoading} period={period}/>} {tab==='CAPS'&&<MarketCapSection indices={indices} loading={marketLoading} period={period}/>} {selected&&<FundDetail r={selected} series={selectedSeries} loading={historyLoading} onClose={()=>setSelected(null)}/>} 
   <footer className="footer"><span><b>Data:</b> Mutual-fund NAV from MFAPI; market indices/sectors from Yahoo Finance chart data.</span><span><b>Score:</b> 35% quality · 25% opportunity · 15% discount · 15% momentum · 10% risk.</span><span><b>Disclaimer:</b> Historical decision-support only. No prediction, guaranteed return or personalized financial advice.</span></footer>
  </div></main>
}
function Spot({label,value,sub}:{label:string;value:string;sub:string}){return <div><small>{label}</small><b>{value}</b><span>{sub}</span></div>}
function FundCard({r,rank,period,onClick}:{r:MF;rank:number;period:Horizon;onClick:()=>void}){const a=action(r);return <button className="panel fund-card" onClick={onClick}><div className="fund-head"><span className="rank-badge">{rank}</span><span className={`state ${actionClass(a)}`}>{a}</span></div><h3>{r.name}</h3><small>{r.category} · Direct Growth</small><div className="fund-metrics"><Metric label={horizon(period)} value={pct(ret(r,period))}/><Metric label="1Y" value={pct(r.ret1y)}/><Metric label="Drawdown" value={`-${r.drawdown.toFixed(1)}%`}/></div><div className="score-line"><span>All Score</span><Score v={r.total}/></div><div className="mini-grid"><span>Quality <b>{score(r.quality)}</b></span><span>Opportunity <b>{score(r.opportunity)}</b></span><span>Discount <b>{score(r.discount)}</b></span><span>Risk <b>{score(r.risk)}</b></span></div><div className="why-line">Why: {why(r)}</div></button>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric-card"><small>{label}</small><b>{value}</b></div>}
function why(r:MF){const reasons:string[]=[];if(r.rsi<45)reasons.push('RSI weakness');if(r.drawdown>7)reasons.push('deep correction');if(r.ma20>r.ma50)reasons.push('MA20 above MA50');if(r.ret1y>12)reasons.push('strong 1Y quality');if(r.volatility<22)reasons.push('controlled volatility');return reasons.slice(0,3).join(' · ')||'balanced long-term setup';}
function LoserPanel({title,rows,period,onSelect}:{title:string;rows:MF[];period:Horizon;onSelect:(r:MF)=>void}){return <section className="panel loser-panel"><div className="panel-head"><div><div className="kicker">WEAKNESS RADAR</div><h2>{title}</h2><p>Only negative performers are listed. A decline alone is not a buy signal.</p></div><span className="tag">DECLINE</span></div>{rows.length?rows.map((r,i)=><button className="loser-row" key={r.id} onClick={()=>onSelect(r)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{r.name}</b><small>RSI {Math.round(r.rsi)} · DD {r.drawdown.toFixed(1)}% · {action(r)}</small></div><Change v={ret(r,period)}/><Score v={r.total}/></button>):<div className="empty-state">No negative {period.toLowerCase()} equity-fund returns in the current dataset.</div>}</section>}
function MarketCapSection({indices,loading,period}:{indices:Market[];loading:boolean;period:Horizon}){return <section className="section-block"><div className="section-head"><div><div className="kicker">MARKET CAP REGIME</div><h2>Nifty 50 · Next 50 · Midcap · Smallcap · Broad Market</h2><p>Use market breadth to decide whether to lean toward large, mid or small-cap funds.</p></div><span className="tag">MARKET BREADTH</span></div><div className="cap-grid">{loading?[1,2,3,4,5].map(i=><div className="panel" key={i}><Skeleton className="cap-sk"/></div>):indices.map(x=><div className="panel cap-card" key={x.symbol}><div className="cap-top"><b>{x.name}</b>{x.current!==null&&<Change v={marketRet(x,period)}/>}</div>{x.current===null?<><span className="state bad">DATA UNAVAILABLE</span><small>No score assigned</small></>:<><div className="cap-sub">1M {pct(x.monthly)} · 3M {pct(x.quarter)}</div><div className="cap-bottom"><span className={`state ${x.state==='STRONG'||x.state==='POSITIVE'?'good':x.state==='WATCH'?'warn':'bad'}`}>{x.state}</span><span>RSI {Math.round(x.rsi)} · DD {pct(-x.drawdown)}</span></div></>}</div>)}</div></section>}
function SectorSection({sectors,loading,period}:{sectors:Market[];loading:boolean;period:Horizon}){const sorted=[...sectors].sort((a,b)=>a.weekly-b.weekly);return <section className="section-block"><div className="section-head"><div><div className="kicker">SECTOR ROTATION</div><h2>Which sectors fell, which are strong?</h2><p>Weekly weakness is shown alongside monthly trend and setup quality.</p></div><span className="tag">SECTOR HEATMAP</span></div><div className="panel sector-panel"><div className="sector-table head"><span>SECTOR</span><span>WEEKLY</span><span>MONTHLY</span><span>RSI</span><span>SETUP</span><span>STATE</span></div>{loading?[1,2,3,4,5,6].map(i=><Skeleton key={i} className="sector-sk"/>):sorted.map((s,i)=><div className="sector-table" key={s.symbol}><span><b>{String(i+1).padStart(2,'0')} {s.name}</b><small>3M {pct(s.quarter)} · DD {pct(-s.drawdown)}</small></span><Change v={s.weekly}/><Change v={s.monthly}/><span>{Math.round(s.rsi)}</span><Score v={s.setup}/><span className={`state ${s.state==='STRONG'||s.state==='POSITIVE'?'good':s.state==='WATCH'?'warn':'bad'}`}>{s.state}</span></div>)}</div></section>}
function MetalsSection({gold,silver,goldW,goldM,silverW,silverM,onSelect}:{gold:MF[];silver:MF[];goldW:MF[];goldM:MF[];silverW:MF[];silverM:MF[];onSelect:(r:MF)=>void}){return <section className="section-block metals-block"><div className="section-head"><div><div className="kicker">PRECIOUS METALS · MUTUAL FUNDS ONLY</div><h2>Gold & Silver — no direct ETFs</h2><p>Only mutual-fund / FoF schemes are included. Direct ETF instruments are excluded.</p></div><span className="tag gold">GOLD + SILVER</span></div><div className="two-grid"><MetalCard title="Gold Mutual Funds" rows={gold.slice(0,2)} weekly={goldW} monthly={goldM} onSelect={onSelect}/><MetalCard title="Silver Mutual Funds" rows={silver.slice(0,2)} weekly={silverW} monthly={silverM} onSelect={onSelect}/></div></section>}
function MetalCard({title,rows,weekly,monthly,onSelect}:{title:string;rows:MF[];weekly:MF[];monthly:MF[];onSelect:(r:MF)=>void}){return <div className="panel metal-card"><div className="panel-head"><h2>{title}</h2><span className="tag gold">TOP 2</span></div><div className="metal-columns"><div><small className="column-title">BEST BY ALL SCORE</small>{rows.map((r,i)=><button key={r.id} onClick={()=>onSelect(r)} className="metal-row"><span>{i+1}. <b>{r.name}</b><small>1Y {pct(r.ret1y)} · RSI {Math.round(r.rsi)}</small></span><Score v={r.total}/></button>)}</div><div><small className="column-title">TOP LOSERS — WEEKLY / MONTHLY</small><div className="metal-loser-title">Weekly</div>{weekly.length?weekly.slice(0,2).map(r=><button key={`w${r.id}`} onClick={()=>onSelect(r)} className="metal-mini"><b>{r.name}</b><Change v={r.weekly}/></button>):<div className="empty-mini">No negative weekly return</div>}<div className="metal-loser-title">Monthly</div>{monthly.length?monthly.slice(0,2).map(r=><button key={`m${r.id}`} onClick={()=>onSelect(r)} className="metal-mini"><b>{r.name}</b><Change v={r.monthly}/></button>):<div className="empty-mini">No negative monthly return</div>}</div></div></div>}
function FundTable({rows,loading,period,onSelect}:{rows:MF[];loading:boolean;period:Horizon;onSelect:(r:MF)=>void}){return <section className="section-block"><div className="section-head"><div><div className="kicker">MUTUAL FUND UNIVERSE</div><h2>All Equity Funds — ranked by All Score</h2><p>Click a fund for NAV history and score explanation.</p></div></div><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>#</th><th>Fund</th><th>{horizon(period)}</th><th>1Y</th><th>6M</th><th>DD</th><th>RSI</th><th>Quality</th><th>Opportunity</th><th>All Score</th><th>Action</th></tr></thead><tbody>{loading?[1,2,3,4,5,6].map(i=><tr key={i}><td colSpan={11}><Skeleton className="row-sk"/></td></tr>):rows.map((r,i)=><tr key={r.id} onClick={()=>onSelect(r)}><td>{i+1}</td><td><b>{r.name}</b><small>{r.category}</small></td><td><Change v={ret(r,period)}/></td><td><Change v={r.ret1y}/></td><td><Change v={r.ret6m}/></td><td>{r.drawdown.toFixed(1)}%</td><td>{Math.round(r.rsi)}</td><td><Score v={r.quality}/></td><td><Score v={r.opportunity}/></td><td><Score v={r.total}/></td><td><span className={`state ${actionClass(action(r))}`}>{action(r)}</span></td></tr>)}</tbody></table></div></div></section>}
function FundDetail({r,series,loading,onClose}:{r:MF;series:{date:string;nav:number;short:string}[];loading:boolean;onClose:()=>void}){return <section className="panel detail-panel"><div className="panel-head"><div><div className="kicker">FUND RESEARCH</div><h2>{r.name}</h2><p>{r.category} · latest NAV {r.nav?`₹${r.nav.toFixed(2)}`:'—'} · {r.navDate||'—'}</p></div><div className="detail-actions"><span className={`state ${actionClass(action(r))}`}>{action(r)}</span><button onClick={onClose}>Close</button></div></div><div className="metric-cards"><Metric label="Daily" value={pct(r.daily)}/><Metric label="Weekly" value={pct(r.weekly)}/><Metric label="Monthly" value={pct(r.monthly)}/><Metric label="1Y" value={pct(r.ret1y)}/><Metric label="52W DD" value={`-${r.drawdown.toFixed(1)}%`}/><Metric label="RSI" value={String(Math.round(r.rsi))}/></div><div className="detail-score-grid"><div><h3>Score breakdown</h3><ScoreLine label="Quality" value={r.quality}/><ScoreLine label="Opportunity" value={r.opportunity}/><ScoreLine label="Discount" value={r.discount}/><ScoreLine label="Momentum" value={r.momentum}/><ScoreLine label="Risk" value={r.risk}/><div className="big-score"><span>All Score</span><Score v={r.total}/></div></div><div><h3>Why this fund?</h3><p className="research-copy">{why(r)}. The score rewards durable 6–12 month performance and controlled volatility while still giving credit for recent weakness and recovery.</p><div className="research-grid"><span>MA20 <b>{r.ma20>0?'Tracked':'—'}</b></span><span>MA50 <b>{r.ma50>0?'Tracked':'—'}</b></span><span>Volatility <b>{r.volatility.toFixed(1)}%</b></span><span>1Y return <b>{pct(r.ret1y)}</b></span></div></div></div><div className="detail-chart">{loading?<Skeleton className="chart-sk"/>:series.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={series}><defs><linearGradient id="navFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#caa42e" stopOpacity={.28}/><stop offset="100%" stopColor="#caa42e" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#edf0f3" vertical={false}/><XAxis dataKey="short" tick={{fontSize:9}} minTickGap={35}/><YAxis tick={{fontSize:9}} domain={['auto','auto']}/><Tooltip formatter={(v:any)=>[`₹${Number(v).toFixed(2)}`,'NAV']}/><Area type="monotone" dataKey="nav" stroke="#b58b17" fill="url(#navFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="empty-state">NAV history unavailable.</div>}</div></section>}
function ScoreLine({label,value}:{label:string;value:number}){return <div className="score-line detail"><span>{label}</span><div className="score-bar"><i style={{width:`${score(value)}%`}}/></div><Score v={value}/></div>}
function LongTermSection(){return <section className="section-block"><div className="section-head"><div><div className="kicker">LONG-TERM FILTER</div><h2>Parameters added for better 7–15 year decisions</h2><p>The engine is designed to avoid chasing only the latest weekly or monthly winner.</p></div></div><div className="six-grid"><Info n="01" title="All Score" text="35% quality + 25% opportunity + 15% discount + 15% momentum + 10% risk."/><Info n="02" title="Long-term quality" text="1Y and 6M return quality plus a volatility penalty reward durable performance."/><Info n="03" title="Drawdown" text="Distance below the 52-week high identifies meaningful corrections without assuming every fall is attractive."/><Info n="04" title="RSI + trend" text="Separates oversold weakness from a deteriorating trend using RSI and moving-average structure."/><Info n="05" title="Sector + market-cap context" text="Use sector rotation and Nifty breadth to decide where additional SIP weight may be appropriate."/><Info n="06" title="Diversification" text="The SIP engine avoids concentrating the full monthly amount in one fund, theme or market-cap bucket."/></div></section>}
function Info({n,title,text}:{n:string;title:string;text:string}){return <div className="panel info-card"><span>{n}</span><b>{title}</b><p>{text}</p></div>}
